### ISSUE TITLE
Line wrapping and scrolling behaves weird with emojis

### ISSUE THREAD

**Issue by Joshix-1** [gwsw/less#637]
```bash
for _ in $(seq 1000) ; do printf "\xf0\x9f\x91\xa9\xf0\x9f\x8f\xbd\xe2\x80\x8d\xe2\x9d\xa4\xef\xb8\x8f\xe2\x80\x8d\xf0\x9f\x92\x8b\xe2\x80\x8d\xf0\x9f\x91\xa8\xf0\x9f\x8f\xbc" ; done | less
```

after running that it should just display 1000 times the [👩🏽‍❤️‍💋‍👨🏼](https://emojipedia.org/kiss-woman-man-medium-skin-tone-medium-light-skin-tone)

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/30b14f90-3bdf-43a8-b684-6a86728a44f4" />

it kinda does it, but the line breaks are within the emojis which is wrong.

After a bit of pressing ARROW UP, ARROW DOWN, PAGE UP and PAGE DOWN i got less to show the following:

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/dd3ef100-c3b4-4959-9553-988e2ababf8c" />

It's behaving really strange.

**Comment by polluks** [comment]
ack on Windows terminal

**Comment by gwsw** [comment]
I think the problem is the use of the ZERO WIDTH JOINER character to compose multiple emojis into one. I don't think less can handle this correctly in all cases because different terminals handle such strings differently, and less has no way to know what the current terminal will do. For example, this command
```
printf "\xf0\x9f\x91\xa9\xe2\x80\x8d\xe2\x9d\xa4\xef\xb8\x8f\xe2\x80\x8d\xf0\x9f\x92\x8b\xe2\x80\x8d\xf0\x9f\x91\xa8\n"
```
produces these results:

1. On konsole, kitty, and contour: uses 2 printing positions (a properly composed double-width char).
2. On MacOS terminal: uses 4 printing positions.
3. On xterm, rxvt, urxvt, alacritty, ptyxis, roxterm, tilda, and terminator: uses 7 printing positions (although the actual glyphs printed are different among these terminals).

It seems that the behavior of sequences using ZWJ to join emojis is terminal-specific, so I don't see a way for less to operate "correctly" on all terminals. (I also note that none of vi, vim or nvim display this sequence as a single double-width character.)

**Comment by Joshix-1** [comment]
Unicode defines this byte Sequence to be a single emoji. Anything that doesn't display that correctly should fix their unicode support.

I don't see bad unicode support of other programs as a reason to not properly support unicode.

Could less maybe detect too long lines by reading the cursor position after printing a grapheme?

**Comment by gwsw** [comment]
Where do you see that Unicode defines these sequences to be a single emoji? I see [this page](https://www.unicode.org/emoji/charts/emoji-zwj-sequences.html) that lists "recommended" sequences, and says
>When not available, the ZWJ characters are ignored and a fallback sequence of separate emoji is displayed.  Thus an emoji zwj sequence should only be supported where the fallback sequence would also make sense to a viewer.

I read this as saying that it is acceptable for a renderer to ignore ZWJ sequences and print the individual emojis separately.

**Comment by gwsw** [comment]
I think the best approach is to treat the ZWJ (U+200D) as a binary character, so it will be printed as a hex value rather than sent to the terminal. It would act as if ```LESSUTFCHARDEF``` were set to ```200d:b```. This will make all terminals act the same, and is consistent with how vi, vim and nvim handle ZWJ.

**Comment by avih** [comment]
Well, vi, vim and nvim are all editors which should show individual units to edit, while less is a pager which is supposed to display it how it shows in the terminal, so the comparisons is not exactly apples to apples.

That being said, I agree that less can't know how the terminal would display it, and displaying it as binary is not a bad choice (unless it tests the cursor position etc, which is highly likely to not be worth the runtime test effort).

In addition to U+200D, I think terminals also disagree on the display width of U+2028 LINE SEPARATOR, U+2029 PARAGRAPH SEPARATOR, and to some degree on U+00AD SOFT HYPHEN (iirc all terminals except kitty treat it as width 1 - like Markus Kuhn documented it many years ago in his wcwidth implementation, while kitty treats it as 0).

**Comment by gwsw** [comment]
As it happens, U+2028 and U+2029 are already treated as binary characters (because their General Category is Zl and Zp respectively). The General Category of U+200D on the other hand is Cf. Less thinks that means that it is a "composing" char, meaning it can be sent to the terminal but occupies zero width. Unfortunately that's not how U+200D actually behaves on all terminals. U+00AD also has General Category Cf, so less treats it as a composing char too, which if what you say is correct, means it works correctly only on kitty. So it sounds like the change should be to treat both U+00AD and U+200D as binary rather than composing.

**Comment by avih** [comment]
> So it sounds like the change should be to treat both U+00AD and U+200D as binary rather than composing.

I think that would be OK, but I encourage you to confirm my finding independently, especially about U+00AD (because I think Zl and Zp can be considered binary, but I think U+00AD is used frequently, I think, but not sure, that groff uses it to wrap lines in manpages).

(I did not test this very recently, but I did about a year ago, because I wrote a wcwidth C generator from the unicode data files, and I tested specifically how these codepoints behave in various terminals).

See here https://github.com/jquast/wcwidth/issues/8#issuecomment-2003028586 .

**Comment by avih** [comment]
And re my findings about U+00AD, I did not check how it's implemented in each terminal, but it's possible that most of the terminals simply use the system wcwidth, and this was tested on Alpine linux, which uses musl-libc, and its wcwidth has U+00AD as width 1.

So it's possible that on a system with a different wcwidth implementation the result would be different (though iirc it's width 1 in glibc's wcwidth too).

However, I think most wcwidth implementations are or were originally based on Markus Kuhn's code, and there it explicitly documents U+00AD as width 1, so I think this should be the dominant value by most wcwidth implementations (it is in my wcwidth too, specifically as an overriding value, because, as you said, other than this Cf is width 0).

**Comment by kovidgoyal** [comment]
Just FYI, the way to permanently solve these issues is for less to tell the terminal how many cells it wants to render a particular grapheme in. Nowadays there exists a protocol that allows terminal programs to do this, though it is very new and thus has limited adoption among terminals so far. See the "width" part of https://sw.kovidgoyal.net/kitty/text-sizing-protocol/

It is currently implemented in the the kitty and foot terminals.

That page also contains a proper spec for calculating grapheme width in cells, with a test suite.

**Comment by gwsw** [comment]
@kovidgoyal Thanks, this is interesting. I have only skimmed it so far, but a quick question: does this protocol handle the case being discussed here, where a sequence of several characters are to be combined into a single glyph? In other words, can a client program use this protocol to tell the terminal to display a string of (in the OP's example) ten Unicode characters in a 2-width cell?

**Comment by kovidgoyal** [comment]
On Thu, Jul 24, 2025 at 10:02:32PM -0700, gwsw wrote:
> gwsw left a comment (gwsw/less#637)
>
> @kovidgoyal Thanks, this is interesting. I have only skimmed it so far, but a quick question: does this protocol handle the case being discussed here, where a sequence of several characters are to be combined into a single glyph? In other words, can a client program use this protocol to tell the terminal to display a string of (in the OP's example) ten Unicode characters in a 2-width cell?

yes.

**Comment by avih** [comment]
> I think U+00AD is used frequently, I think, but not sure, that groff uses it to wrap lines in manpages

This seems to be incorrect. Testing groff on ubuntu and windows with `groff -man -Tutf8 less.nro.VER`, and it uses 0xe2 0x80 0x90 when it breaks words at EOL, which is U+2010 HYPHEN.

So I don't know how much U+00AD is used in practice.

**Comment by gwsw** [comment]
Unfortunately, my testing indicates that U+00AD is inconsistent among terminals. 
It displays as 1-space wide in xterm, rxvt, urxvt, terminator, konsole, ptyxis, roxterm, tilda, and MacOS terminal.
It displays as 0-space wide in kitty, contour, and alacritty.
So I may need to treat it as binary too.

**Comment by avih** [comment]
> It displays as 0-space wide in kitty, contour, and alacritty.

Interesting. Less than a year ago alacritty was definitely 1-hyphen/dash - https://github.com/jquast/wcwidth/issues/8#issuecomment-2003028586 , and I didn't test contour, but they seem to have their own take on Graphem-cluster rendering, disliking wcwidth as an interface for this, and I don't know what data they use which results in ignoring U+00AD at the input.

To be clear, wcwidth is generally OK for handling graphem clusters, as the application should keep accumulating the grapheme cluster as long as wcwidth keeps returning 0, where the width is the wcwidth value before the first 0.

There are, however, rare cases where wcwidth is not enough, where whether/how a codepoints affects the cluster width depends on the prior codepoint (Emoji related) - which wcwidth doesn't maintain as it's stateless. However, this is where the less-used wcswidth should come in, which takes a sequence of codepoints and calculates their total width, as it can take into account relations between consecutive codepoints at the sequence (whether it does that or not depends on the implementation).

And of course, the main problem with this subject is that the terminal and the application must agree on the on-screen width of a sequence of codepoints, but because historically the libc wcwidth may be outdated (or doesn't exist - like on Windows), many terminals and applications which care about it - like less - bring their own unicode database, and use that in conjunction with their own width calculations, so disagreement between the terminal and the application can happen for graphemes clusters which are not in common use.

For instance, the windows terminal (v1.22) considers it width 0 and therefore thinks it extends the grapheme clister, but because it renders as a hyphen, it ends up rendered on top of the previous glyph, for instance `O` (Oh), U+00AD, `X` looks (incorrectly) like this, which is clearly not a correct semantic use of soft-hyphen:
<img width="43" height="31" alt="Image" src="https://github.com/user-attachments/assets/65c3681a-2b94-436e-bfb4-f65461a53dae" /> .

**Comment by avih** [comment]
And as for what less should do with U+00AD, I think it depends on the potential consequnces in cases where it disagrees with the terminal on its width.

If less considers it width 0, then it can result in issues if the terminal considers it 1, because then less can think the line fits in the terminal width, while the terminal may wrap the line because it's too long.

However, if less considers it width 1, then the worst case is that the terminal thinks it's 0, which - only in cases where the line is generally too-long to fit on screen, would cause the line to end on-screen before the right edge of the terminal, which may be considered not really an issue, with the added value that it typically gets rendered correctly.

But still, a bullet-proof solution which considers it binary still works, even if it may render not-as-intended, and especially assuming it's not in common use, as this would not be a too-common annoyance.

**Comment by gwsw** [comment]
I don't think there's a perfect solution, but treating it as binary seems to be least likely to cause erroneous display, even if it's probably almost never the most desired behavior on any specific system. If a user is working in an environment where they know it would be better to treat it as printable 1-width or printable 0-width, they can override the default using LESSUTFCHARDEF.

**Comment by gwsw** [comment]
In 023bc6404b41ccb77f74d7a267edce1b0a6b2dfe, U+00AD and U+200D are treated as binary.

**Comment by avih** [comment]
For future reference, SOFT-HYPHEN (SHY) specifically has complex history, and its semantic has been largely one of two:
1. Visible character inserted by a formatting tool to indicate that the a word was broken here, typically before a line break, and SHY has its own codepoint to distinguish it from normal HYPHEN which is part of the original text.
2. Formatting hint which is part of the original text, suggesting that if word-break is needed, then it can be done here. Unclear whether it's visible when a word-break happened, or whether some other visible character is used.

1 is the ISO-8559-1 semantics and largely the original, while 2 is a conflicting Unicode semantics which came later, while claiming compatibility with ISO-8559-1 for codepoints 0-0xFF.

To me personally 1 makes more sense, because 2 effectively means that it's useful only if inserted between every two syllables at the input or some such (if it's only inserted every few words then I don't see how it's useful to a word-wrapper), which likely roughly double the input text size.

In terminals there's some concensus that 1 should be applied:
https://en.wikipedia.org/wiki/Soft_hyphen
https://jkorpela.fi/shy.html
https://www.unicode.org/L2/L2003/03155r-kuhn-soft-hyphen.pdf

As far as terminals emulators go, with interpretation 1 it should always be visible and occupying its own space (not width 0), because it was inserted by a formatting tool to visibly indicate word-break. This is indeed what most terminals do, though some display it as space, unclear if only due to missing glyph, and few always ignore it at the input.

With interpretation 2, terminals should display it visbly, occupying its own space if it's the last char at the line, and otherwise don't display it. There's no terminal which I know of which does that (not even Windows terminal mentioned above, because it always both considers it width 0 and also unconditionally renders it - overlaying the previous char, which always resulting in incorrect output).

In the context of a reader application like "less", I think it's obvious that if it occures as part of the input then generally it should not be displayed.

If it occures right before a line-break at the input, or if less itself break the line at this point, then some visible hyphen may be displayed. But less doesn't display a hyphen on word-break AFAIK, and also terminals don't always agree on how it should be displayed, so effectively I think less should simply always ignore it at the input (and never add it voluntarily at the output, which is already the case).

And, as mentioned above, groff inserts a normal hyphen (not SHY) when it breaks a word at EOL.

**Comment by gwsw** [comment]
Fixed in 023bc6404b41ccb77f74d7a267edce1b0a6b2dfe.

**Comment by Joshix-1** [comment]
Using kitty it now looks like the following:

<img width="1920" height="1079" alt="Image" src="https://github.com/user-attachments/assets/e0d61797-3a3e-4d3c-9317-8504d8666337" />

In konsole I can still get a similar bug, just that it now looks worse

<img width="1918" height="1079" alt="Image" src="https://github.com/user-attachments/assets/a67b7a6d-8b64-45b0-8795-01629ad159c3" />

**Comment by gwsw** [comment]
Hm, looks like the EMOJI MODIFIER characters are also handled differently on different terminals. I guess those also need to be treated as binary characters. I've done that in c1e2880cecfcc5a10f39321df97dc9e8fac67ac6.

There is still one issue though: the heart U+2764 followed by the variation selector U+FE0F display differently in different terminals. It is one space wide in xterm, rxvt, urxvt, terminator, tilda, roxterm and ptyxis; while it is two spaces wide in kitty, alacritty, konsole and contour. I don't see the rationale for it being double width; less thinks it is single width based on the Unicode tables. Making the VARIATION SELECTORs be binary may be the best option but I'm still investigating. BTW I also notice that vi, vim and nvim all mishandle a file containing that heart sequence on some of those terminals.

I'm sure there are still more multi-char emoji sequences that are printed differently on different terminals. This is a major pain. I think Unicode has gone off the rails with these multi-character emoji sequences.

**Comment by gwsw** [comment]
In a69d8e4639dd8e7d27bf3d0eb5f98d98dd1fc662 I changed all the VARIATION SELECTOR chars to binary as well. It's a shame but I don't see a reasonable alternative.

**Comment by kovidgoyal** [comment]
On Sun, Aug 10, 2025 at 03:24:20PM -0700, gwsw wrote:
> gwsw left a comment (gwsw/less#637)
>
> Hm, looks like the EMOJI MODIFIER characters are also handled differently on different terminals. I guess those also need to be treated as binary characters. I've done that in c1e2880cecfcc5a10f39321df97dc9e8fac67ac6.
>
> There is still one issue though: the heart U+2764 followed by the variation selector U+FE0F display differently in different terminals. It is one space wide in xterm, rxvt, urxvt, terminator, tilda, roxterm and ptyxis; while it is two spaces wide in kitty, alacritty, konsole and contour. I don't see the rationale for it being double width; less thinks it is single width based on the Unicode tables. Making the VARIATION SELECTORs be binary may be the best option but I'm still investigating. BTW I also notice that vi, vim and nvim all mishandle a file containing that heart sequence on some of those terminals.

The rationale is here:
https://sw.kovidgoyal.net/kitty/text-sizing-protocol/#var-select

And currently kitty uses less as its default pager for viewing
scrollback, if you break display of variation selectors it is
going to lead to a *lot* of bug reports for you.

The Unicode standard is quite clear on variation selectors, please
follow it.

**Comment by gwsw** [comment]
Can you point me to the part of the Unicode standard that specifies the behavior of variation selectors?

Regardless of what the spec says, however, the majority of terminals don't handle variation selectors the way your document describes. If supporting the spec means breaking xterm, urxvt, terminator, etc, that's not a viable approach. Either I have to treat variation selectors as binary, which works on all terminals, or there needs to be some way to detect the terminal's behavior, ideally automatically or if that's not possible, perhaps via an environment variable.

**Comment by kovidgoyal** [comment]
On Sun, Aug 10, 2025 at 06:53:31PM -0700, gwsw wrote:
> gwsw left a comment (gwsw/less#637)
>
> Can you point me to the part of the Unicode standard that specifies the behavior of variation selectors?

https://www.unicode.org/reports/tr51/#Emoji_Variation_Sequences

FE0F changes text presentation codepoints to emoji presentation code
points and emoji presentation codepoints have width two.

Similarly FE0E changes emoji presentation to text presentation. You need
to deal correctly with both. And no replacing them with reverse video
HEX codes is not dealing correctly with them.

> Regardless of what the spec says, however, the majority of terminals don't handle variation selectors the way your document describes. If supporting the spec means breaking xterm, urxvt, terminator, etc, that's not a viable approach.

So because of bugs in xterm and urxvt you want to make less unuseable on
all terminals? I dont follow the logic here. There is a clear spec, some
terminals adhere to it, some do not. less should work on terminals that
adhere to it, by default, with an *option* to break the text on
terminals that dont adhere to the spec. That is the only sane way
forward.

> Either I have to treat variation selectors as binary, which works on all terminals, or there needs to be some way to detect the terminal's behavior, ideally automatically or if that's not possible, perhaps via an environment variable.

Replacing/ignoring/munging etc. the variation selectors is not *working*, it's
breaking the display of the text.

And if you want to query terminal behavior for this doing so is done by:
send carriage return, then text using FEOF, then query the cursor
position, then send carriage return and clear to end of line.

Though IMO dont query, just follow the spec and if users use broken
terminals, then have some config mechanism for them.

And note that you cannot use wcwidth() to get the width of a text
string, widths can only hope to be correctly calculated by wcswidth()
and even then, only by passing it the screen width. It sucks, but that
is the standard we have.

In any case it's your project, you do whatever you want. If you want the
default behavior of less to be broken with variation selectors, that's
your choice. In that case, at least give us a command
line flag or env var or *something* to do the right thing with them.
Otherwise, less simply becomes unuseable.

**Comment by gwsw** [comment]
I appreciate your viewpoint, but less has to operate reasonably in the real world with existing terminals. Even if, for example, xterm is technically not in conformance with this UTS, xterm is very widely used and I am sure I would also get a lot of bug reports if less fails to work correctly on xterm. Also the UTS is less than a year old, so it's not surprising that many terminals don't comply with it, even if their roadmap is eventually to do so. Even if and when most terminals do fully support the UTS, any particular user may be using an older version of a terminal. Less should not break on a terminal that doesn't support this new protocol, now or ever.

In any case, I understand the issue better now and I will do some investigation as to what could be done to produce the best feasible behavior on all terminals. Querying the terminal as you describe is a possibility, but I don't know if that can be done safely, without race conditions, if the user is typing input at the same time that less queries the terminal and tries to read the response.

**Comment by kovidgoyal** [comment]
On Sun, Aug 10, 2025 at 07:55:38PM -0700, gwsw wrote:
> gwsw left a comment (gwsw/less#637)
>
> I appreciate your viewpoint, but less has to operate reasonably in the real world with existing terminals. Even if, for example, xterm is technically not in conformance with this UTS, xterm is very widely used and I am sure I would also get a lot of bug reports if less fails to work correctly on xterm.

I think I failed to communicate clearly. Replacing variation selectors
with HEX codes in reverse video fails on *all* terminals, xterm, kitty,
everywhere. Fails, in the sense of the text becoming unreadable to less
users. This happens *whenever* there is a variation selector, on *all*
terminals.

Using a wcswidth() implementation that supports variation selectors
fails on *some* terminal emulators, *some* of the time.
To be precise, it will fail to display the text correctly if a variation
selector is present on a line whose width without the variation selector
is close the screen width. And it will fail only on terminal emulators
that are not spec compliant.

To me at least, the choice is a clear one. YMMV.

> Also the UTS is less than a year old, so it's not surprising that many terminals don't comply with it, even if their roadmap is eventually to do so. Even if and when most terminals do fully support the UTS, any particular user may be using an older version of a terminal. Less should not break on a terminal that doesn't support this new protocol, now or ever.

Not at all, the UTS link I posted above is just the latest version of this. Emoji variation
selectors have been in the unicode standard for about a decade IIRC.
Some quick googling leads me to
https://www.unicode.org/L2/L2017/17103.htm
Indicating a timeline of 2017 unicode version 6

>
> In any case, I understand the issue better now and I will do some investigation as to what could be done to produce the best feasible behavior on all terminals. Querying the terminal as you describe is a possibility, but I don't know if that can be done safely, without race conditions, if the user is typing input at the same time that less queries the terminal and tries to read the response.

Cursor position responses come in the form ESC [ number ; number r
https://vt100.net/docs/vt510-rm/CPR.html

The only way you could confuse that for typing is if the user types ESC
and [ etc. just while doing querying, a negligible probability.
Of course, this can be made completely
robust by using the kitty keyboard protocol which makes disambiguating
user input from escape code responses completely rigorous apart form
lots of other benefits.
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

All the best and I look forward to seeing how you solve this, I have
been happily using less for about twenty years now, and it is the default
pager used to view scrollback and help in kitty. Feel free to ping me if
I can provide more clarity.

**Comment by gwsw** [comment]
>The only way you could confuse that for typing is if the user types ESC
and [ etc. just while doing querying, a negligible probability.

I don't think it's totally negligible, since on many terminals, arrow keys etc emit a sequence starting with ```ESC [```. 

>Replacing variation selectors
with HEX codes in reverse video fails on *all* terminals, xterm, kitty,
everywhere. Fails, in the sense of the text becoming unreadable to less
users. 

I view it a bit differently. Displaying a hex code is unfortunate and obviously not what the user wants to see, but it's not a failure. A failure is when less doesn't know what's displayed on the screen. This can cause text to be scrolled off the top inadvertently or things like that, totally breaking the display and causing disruption far removed from the point where the emoji sequence occurs.

Anyway, I'll see what I can do to support both terminals that support variation selectors and those that don't. This is much more complicated than I initially understood.

**Comment by kovidgoyal** [comment]
On Sun, Aug 10, 2025 at 08:31:57PM -0700, gwsw wrote:
> gwsw left a comment (gwsw/less#637)
>
> >The only way you could confuse that for typing is if the user types ESC
> and [ etc. just while doing querying, a negligible probability.
>
> I don't think it's totally negligible, since on many terminals, arrow keys etc emit a sequence starting with ```ESC [```.
Those never end with r, they end with some other ascii letter.
You basically need to parse the input stream for the regex:
\x1b\[[0-9;]+r

Nothing else the terminal sends you will ever match that unless the user
actually types or pastes those bytes. For pasting at least I hope less
uses bracketed paste mode which solves that issue.

>
> >Replacing variation selectors
> with HEX codes in reverse video fails on *all* terminals, xterm, kitty,
> everywhere. Fails, in the sense of the text becoming unreadable to less
> users.
>
> I view it a bit differently. Displaying a hex code is unfortunate and obviously not what the user wants to see, but it's not a failure. A failure is when less doesn't know what's displayed on the screen. This can cause text to be scrolled off the top inadvertently or things like that, totally breaking the display and causing disruption far removed from the point where the emoji sequence occurs.

Why is that though? If you turn off wrap mode (DECAWM) when rendering
lines, and do the wrapping yourself, a mismatch in width calculation
between less and the terminal will at worst case one line of corruption,
since the cursor y position will always be what less expects.

>
> Anyway, I'll see what I can do to support both terminals that support variation selectors and those that don't. This is much more complicated than I initially understood.

Yup, apologies I am probably wasting too much of your time :)
I will shut up now.

**Comment by gwsw** [comment]
There are several changes in 4ad1ce1c9a3d617b69937675858b4211751eee5f:
1. By default, emoji modifiers (the skin color, hair color, and variation selectors) are just omitted from the output rather than being displayed as hex codepoints. This is visually better and should work in all terminals. Omitting the modifiers results in output that is reasonably close to the intended display; at least it's better than using the hex display.
2. On terminals with full or partial support for the modifiers, you can use the LESSUTFCHARDEF environment variable to set selected modifiers to be "composing" rather than "deleted" (see the change in the man page).
3. You can also use LESSUTFCHARDEF to select other characters to be deleted, although I don't yet know of a reason that one would use this feature.

I don't consider these changes to be fully tested, since I have not found any terminal that fully supports all the modifiers as described in the Unicode UTS. Kitty comes close but there are bugs that prevent testing VS15. For example, this prints a single-width whale as it should:
```
printf "\xf0\x9f\x90\x8b\xef\xb8\x8e\n"
```
However, this prints an "A" followed by space instead of an "A" followed by a whale:
```
printf "A\xf0\x9f\x90\x8b\xef\xb8\x8e\n"
```
Even worse, this hangs the kitty process:
```
printf "\xf0\x9f\x92\x8b\xf0\x9f\x90\x8b\xef\xb8\x8e\n"
```
However, the testing I've done without using VS15 seems like things are working as intended.

**Comment by kovidgoyal** [comment]
@gwsw: Those bugs were fixed already, IIRC. Update to kitty 0.42.2 and
you should be fine, if not, do let me know. There is currently only one
known (unicode related) bug in 0.42.2 (fixed in master) https://github.com/kovidgoyal/kitty/issues/8848

**Comment by gwsw** [comment]
Thanks, those two bugs are indeed fixed in kitty 0.42.2.
I have fixed the support for VS15 in dcac8f3981d2f286e2e870bf09684b311fafef36.
As far as I know, support for emojis in less is now complete.

**Comment by g-branden-robinson** [comment]
> > I think U+00AD is used frequently, I think, but not sure, that groff uses it to wrap lines in manpages

No.

_groff_char_(7):
```
   Eight‐bit encodings and Latin‐1 supplement
     ISO 646 is a seven‐bit code encoding 128 code points; eight‐bit
     codes are twice the size.  ISO Latin‐1 (8859‐1) allocated the
     additional space to what Unicode calls “C1 controls” (control
     characters) and the “Latin‐1 supplement”.  The C1 controls are
     neither printable nor usable as GNU troff input.

     GNU troff handles two Latin‐1 supplement characters specially, and
     never produces them as output.

     NBSP   encodes a no‐break space; it maps to \~, the adjustable non‐
            breaking space escape sequence.

     SHY    encodes a soft hyphen; it maps to \%, the hyphenation
            control escape sequence.
```

Nota bene "**never produces them as output**".

[When we someday get GNU _troff_ converted to expect UTF-8 input](https://savannah.gnu.org/bugs/?40720), I anticipate that we'll handle the input sequence 0xC2 0xAD the same way.

> This seems to be incorrect. Testing groff on ubuntu and windows with `groff -man -Tutf8 less.nro.VER`, and it uses 0xe2 0x80 0x90 when it breaks words at EOL, which is U+2010 HYPHEN.

Right, and if the terminal's character encoding is not UTF-8, as with `-T ascii`, _grotty_ uses a different character to mark a hyphenation break.
